faq page
germanodusha/travelex pull request #27
Opened 2021-11-17 07:57 UTC by guigallo

#13

2021-11-17 14:00 UTC, brunacabeco commented
@guigallo 'Dúvidas Frequentes' é em preto e são 6 perguntas.

2021-11-17 16:15 UTC, brunacabeco requested changes
- [ ] 'Dúvidas Frequentes' é em Preto
- [x]  São 6 perguntas no total
- [x] Tirar react page scroller da parte das perguntas
- [ ] O cabeçalho não muda de cor quando passa pra segunda página. Permanece colorido.
- [ ] O scroll está passando direto do rodapé e leva pra uma página cinza que não tem como retornar via scroll up pra cima

2021-11-22 15:23 UTC, brunacabeco commented
@guigallo  não estou conseguindo abrir a página de faq para aprovar este pr 

<img width="1280" alt="Captura de Tela 2021-11-22 às 12 20 03" src="https://user-images.githubusercontent.com/82957414/142887798-06ee0f95-ff0e-474d-ad0f-ff65035ec193.png">

2021-11-22 22:04 UTC, guigallo commented
@brunacabeco mandei o fix desse PR

2021-11-23 17:40 UTC, brunacabeco approved these changes

2021-11-23 18:04 UTC, merged