Feat/#6
germanodusha/travelex pull request #40
Opened 2021-12-03 03:11 UTC by guigallo

2021-12-03 14:28 UTC, brunacabeco requested changes
- [ ] Os títulos da coluna esquerda são em caixa alta
<img width="158" alt="Captura de Tela 2021-12-03 às 11 06 47" src="https://user-images.githubusercontent.com/82957414/144615747-5babd663-0f12-440c-ba57-d625d882b396.png">

- [ ] na direita, tem sempre uma imagem de fundo com blur (mesmo do institucional)
<img width="566" alt="Captura de Tela 2021-12-03 às 11 09 50" src="https://user-images.githubusercontent.com/82957414/144616452-79712dab-a5cd-4b5c-bdf3-d84dfdb4c862.png">

- [ ] Mudar ordem das categorias da coluna da esquerda para:
Trade Finance
Trade Service
Hedge
Assessoria e serviços
Análises, registros e declarações

- [ ] Colocar hover de tracinho
<img width="160" alt="Captura de Tela 2021-12-03 às 11 20 42" src="https://user-images.githubusercontent.com/82957414/144618956-8b161f87-a9e5-4c31-bff9-c08217d5d204.png">

- [ ] Travar o conteúdo da direita para não embolar com o cabeçalho (igual na página institucional)

<img width="1280" alt="Captura de Tela 2021-12-03 às 11 21 08" src="https://user-images.githubusercontent.com/82957414/144619054-c79c5526-332b-4160-b040-b2aca5f3458f.png">


**o clique na coluna da esquerda muda todo o conteúdo da área de texto da direita.**

- [ ] Quando usuário clica, por exemplo, no primeiro item, na área de conteúdo à direita aparece um frase de destaque em negrito

- [ ] Se usuário der scroll, a imagem sobe junto com o texto em destaque, e abaixo disso tem o texto descritivo para atualizarmos em markdown. Nesse documento https://docs.google.com/document/d/12trTm0QRYFET9001Dp0iuQ8KgC2aYG9Kwcf6PtuUBzo/edit# , a partir da página 8, está o rascunho de contéudo pra você entender do que se trata.

2021-12-07 03:36 UTC, guigallo commented
@brunacabeco o conteúdo dos serviços precisa ser markdown mesmo? hoje está só como texto simples

2021-12-07 14:00 UTC, brunacabeco commented
> @brunacabeco o conteúdo dos serviços precisa ser markdown mesmo? hoje está só como texto simples

Precisa, Gui! Porque terão títulos, subtítulos, lista numerada. São textinhos mais complexos.

2021-12-08 13:02 UTC, guigallo commented
> * [ ]  Se usuário der scroll, a imagem sobe junto com o texto em destaque, e abaixo disso tem o texto descritivo para atualizarmos em markdown. Nesse documento https://docs.google.com/document/d/12trTm0QRYFET9001Dp0iuQ8KgC2aYG9Kwcf6PtuUBzo/edit# , a partir da página 8, está o rascunho de contéudo pra você entender do que se trata.

@brunacabeco criei uma issue especialmente para esse item. Para pode fechar esse PR

2021-12-09 14:51 UTC, merged